
paths:
  base_dir: ${hydra:runtime.cwd}/simulation
  outputs_dir: outputs
  agents_dir: agents_personas
  bingo_board_dir: bingo_boards
  bingo_output_dir: bingo_outputs
  bingo_master_file: bingo_boards/alumni-simple-boards.json
  agent_memories_dir: agent_memories
  long_term_memories: long_term
  short_term_memories: short_term

debug: true

hydra:
  run:
    dir: outputs/runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: outputs/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: true 

defaults:
  - _self_
  - agent: agent
  - conversation: conversation
  - environment: time_dependent


experiment: 
  max_agents: 10
  experiment_id: null