
paths:
  base_dir: ${hydra:runtime.cwd}/simulation
  outputs_dir: outputs
  agents_dir: agents_personas
  bingo_board_dir: bingo_boards
  bingo_output_dir: bingo_outputs
  bingo_master_file: bingo_boards/alumni-simple-boards.json

debug: true

hydra:
  run:
    dir: outputs/runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: outputs/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: true 

defaults:
  - _self_
  - agent: agent
  - conversation: conversation
  - environment: test
