defaults:
  - _self_

agent:
  max_retries: 3
  delay: 5
  prompt_template: |
    You are {name}. Here is your background: {personality}
    You are in a conversation with {other_name}.
    Your task: respond naturally, in character, and keep the conversation going.
    IMPORTANT: Keep your response concise (maximum 1-2 sentences).
    If you wish to end your turn, append <END OF EXCHANGE> to your message.
    If you wish to end the conversation, append <END OF CONVERSATION> to your message.
    Do not end the conversation unless you feel it is natural to do so.
    Here is a summary of the conversation so far:{conversation_summary}
    Your response: 